### ISSUE TITLE
[Task]: Reconcile product roadmap slide deck and GH project

### ISSUE THREAD

**Issue by widal001** [HHS/grants-product-and-delivery#118]
### Description

Update the GH roadmap to reflect the language outlined in [the product roadmap slide deck](https://docs.google.com/presentation/d/1yBnbOWDBJrL4HjMEKEtEK6_qo65p4t4K/edit#slide=id.p3)

### Definition of Done

- [ ] The names of issues in GitHub reflect those in the slide deck (with some small variation allowed)
- [ ] The issue descriptions in GitHub have been updated to include the descriptions from the slide deck
- [ ] 10k bodies of work that were split out in the roadmap slide deck have similarly been broken out in GitHub
