### ISSUE TITLE
[Task]: Incorporate forecasting into the roadmap

### ISSUE THREAD

**Issue by widal001** [HHS/grants-product-and-delivery#129]
### Description

Julius noted that GET opportunities does not by definition include forecasted opportunities. This will be an important part of the Discovery phase and needs to be accounted for in the product roadmap.

### Definition of Done

- [x] Open questions about forecasted opportunities have been reviewed with Julius and their answers have been documented in a way the team can access them
- [x] We have decided whether forecasts can be returned with the opportunities endpoint or require their own endpoint
- [x] The product roadmap has been adjusted to reflect decision above
