### ISSUE TITLE
[Task]: Update short-term roadmap slide deck with Nava feedback

### ISSUE THREAD

**Issue by widal001** [HHS/grants-product-and-delivery#156]
### Summary

The [product roadmap slide deck](https://docs.google.com/presentation/d/1yBnbOWDBJrL4HjMEKEtEK6_qo65p4t4K/edit) has been updated to include input from the Nava team about our priorities for the next 3-6 months

### Acceptance criteria

- [x] Slides have been updated to reflect the set of 30k deliverables we'll focus on for the next 3-6 months
- [x] All comments have been resolved.
- [x] Outdated slides have been hidden (or removed)
- [x] Final changes have been copied over into the [public version of the roadmap slide deck](https://docs.google.com/presentation/d/1bW4wKfUq5riRPaXZCmGgQz2jQwTLMnrA/edit#slide=id.p3)
