### ISSUE TITLE
[Task]: Create delivery dashboard 10k deliverables and sub-tasks

### ISSUE THREAD

**Issue by widal001** [HHS/grants-product-and-delivery#164]
### Summary

Help the Nava team plan for the delivery dashboard 30k deliverable by creating the tickets.

### Acceptance criteria

- [x] 10k deliverable tickets have been created and added to the roadmap
- [x] Milestones have been created
- [x] Issues have been added to those milestones
