### ISSUE TITLE
Create GitHub projects board for the comms team

### ISSUE THREAD

**Issue by widal001** [HHS/grants-product-and-delivery#171]
### Summary

Help the comms team create a GitHub project board to manage communication activities related to simpler.grants.gov

### Tasks

- [x] Create a demo board to showcase options for organizing comms activities
- [x] Meet with the comms team to refine structure of the comms board using the demo board
- [x] Recreate the demo board within the HHS org

### Acceptance criteria

- [x] A comms board has been created under the HHS organization and associated with the simpler-grants-gov repo
- [x] All of the members of the comms team have been added to the project
