### ISSUE TITLE
Prepare for roadmap planning session on 3/21

### ISSUE THREAD

**Issue by widal001** [HHS/grants-product-and-delivery#181]
### Summary

Prepare for the collaborative planning exercise with Nava that will be held on 3/21. The goal of this session is to get the team to think about what needs to be accomplished by the end of this year.

### Acceptance criteria

- [ ] Existing 30k tickets have been added to the mural board that Sarah created
- [ ] The planning session has been held
- [ ] Updates that need to be made to the roadmap in GitHub have been updated
