### ISSUE TITLE
Roadmap reconciliation part 2

### ISSUE THREAD

**Issue by widal001** [HHS/grants-product-and-delivery#206]
### Summary

Prepare for and facilitate the second roadmap reconciliation meeting.

### Acceptance criteria

- [x] The objectives and base year 1 targets have been shared with attendees in advance of the meeting
- [x] The agenda and mural board have been shared with attendees in advance of the meeting
- [x] The meeting is complete and takeaways have been shared in Slack
