### ISSUE TITLE
Prepare SimplerGrants roadmap slide deck for Dale & Renee

### ISSUE THREAD

**Issue by widal001** [HHS/grants-product-and-delivery#284]
### Summary

Prepare a slide deck that walks Dale and Renee through the tentative SimplerGrants roadmap for base year 1.

### Acceptance criteria

- [x] A slide deck has been created that outlines:
  - [x] SimplerGrants objectives
  - [x] Base year 1 outcomes per pillar
  - [x] Agile deliverables for quads 1-3
- [x] This slide deck has been reviewed by:
  - [x] @margaretspring and the Nava leads
  - [x] @lucasmbrown-usds 
  - [ ] @juchang111
