### ISSUE TITLE
Public wiki update - Product Roadmap

### ISSUE THREAD

**Issue by sarahknoppA6** [HHS/grants-product-and-delivery#317]
### Summary

Update the [Product Roadmap](https://wiki.simpler.grants.gov/product/product-roadmap) and [Deliverables](https://wiki.simpler.grants.gov/product/deliverables) section to remove references to the old roadmap and way of tracking deliverables.

### Acceptance criteria

- [x] We've updated the Product section of the wiki to remove references to the old roadmap
- [x] We've updated the link and language to reference the GitHub roadmap
- [x] We've removed outdated deliverables that have been replaced with GitHub issues, while preserving previously completed deliverables
