### ISSUE TITLE
[Task]: Create onboarding checklist page in GitBook

### ISSUE THREAD

**Issue by widal001** [HHS/grants-product-and-delivery#68]
### Description

Create a GitBook page which lists an onboarding checklist for new team members who are added to the Simpler Grants project.

### Definition of Done

- [x] A GitBook page has been created with the following information:
  - [x] List of systems a new team member needs to be added to
  - [x] Links to key resources and background information about the project
  - [x] A checklist that someone can mark off as they get onboarded
  - [x] Initial policy guidelines for public vs private content have been read and signed
- [ ] This checklist has been reviewed with:
  - [ ] Sarah
  - [ ] Esther
  - [ ] Lucas
