### ISSUE TITLE
[Task]: Simpler Grants.gov milestone roadmap slide deck

### ISSUE THREAD

**Issue by widal001** [HHS/grants-product-and-delivery#77]
### Description

Create slide deck that summarizes the key upcoming deliverables in the Simpler Grants.gov product roadmap that can be presented to internal HHS stakeholders

### Definition of Done

- [x] Slide deck has been created
- [x] Slide deck has been reviewed by:
  - [x] Lucas
  - [x] Sarah
  - [x] Adrien
- [x] Slide deck has been presented to the following stakeholders:
  - [x] Renee
  - [x] Dale
  - [x] PMO staff
